/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import trandpl.dao.HrDAO;
import trandpl.dao.jobDAO;
import trandpl.pojo.CurrentUsers;
import trandpl.pojo.jobPojo;

/**
 *
 * @author __roonit
 */
public class HrAddNewJobFrame extends javax.swing.JFrame {

    /**
     * Creates new form HrAddNewJobFrame
     */
    public HrAddNewJobFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblName.setText(CurrentUsers.getName());
        loadData();
    }
    private void loadData(){
        try{
             lblJobId.setText("Job-"+jobDAO.getNewJobId());
            if(txtCompanyName.getText().trim().isEmpty())
                    txtCompanyName.setText(HrDAO.getCompanyNameByHrId(CurrentUsers.getId()));          
        }catch (SQLException ex){
                 JOptionPane.showMessageDialog(null,"DB Error ","Error !",JOptionPane.ERROR_MESSAGE);
                 ex.printStackTrace();
                //return; 
            } 
    }
    private boolean validateInputs(){
        if(txtJobTitle.getText().trim().isEmpty() || skills1.getText().trim().isEmpty() || skills2.getText().trim().isEmpty() || skills3.getText().trim().isEmpty() ||
                skills4.getText().trim().isEmpty() || skills5.getText().trim().isEmpty() || skills6.getText().trim().isEmpty() )
            return false;
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtJobTitle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        skills1 = new javax.swing.JTextField();
        skills3 = new javax.swing.JTextField();
        skills4 = new javax.swing.JTextField();
        skills2 = new javax.swing.JTextField();
        skills5 = new javax.swing.JTextField();
        skills6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        lblJobId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblName.setText("Ronit");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 380, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 980, 140));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Welcome");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txtCompanyName.setBackground(new java.awt.Color(173, 192, 234));
        txtCompanyName.setBorder(null);
        jPanel1.add(txtCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 366, 312, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        btnBack.setBackground(new java.awt.Color(173, 192, 234));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 100, -1));

        btnLogout.setBackground(new java.awt.Color(173, 192, 234));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 600, 100, -1));

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 1060, 10));

        jButton1.setText("Add Job");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 190, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JobPng.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 330, 350));

        txtJobTitle.setBackground(new java.awt.Color(173, 192, 234));
        txtJobTitle.setBorder(null);
        txtJobTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobTitleActionPerformed(evt);
            }
        });
        jPanel1.add(txtJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 364, 310, 34));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        skills1.setBackground(new java.awt.Color(173, 192, 234));
        skills1.setBorder(null);
        skills1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skills1ActionPerformed(evt);
            }
        });
        jPanel1.add(skills1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 240, 32));

        skills3.setBackground(new java.awt.Color(173, 192, 234));
        skills3.setBorder(null);
        skills3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skills3ActionPerformed(evt);
            }
        });
        jPanel1.add(skills3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 240, 32));

        skills4.setBackground(new java.awt.Color(173, 192, 234));
        skills4.setBorder(null);
        skills4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skills4ActionPerformed(evt);
            }
        });
        jPanel1.add(skills4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 240, 32));

        skills2.setBackground(new java.awt.Color(173, 192, 234));
        skills2.setBorder(null);
        skills2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skills2ActionPerformed(evt);
            }
        });
        jPanel1.add(skills2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 240, 32));

        skills5.setBackground(new java.awt.Color(173, 192, 234));
        skills5.setBorder(null);
        skills5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skills5ActionPerformed(evt);
            }
        });
        jPanel1.add(skills5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 240, 32));

        skills6.setBackground(new java.awt.Color(173, 192, 234));
        skills6.setBorder(null);
        skills6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skills6ActionPerformed(evt);
            }
        });
        jPanel1.add(skills6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 240, 32));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Skill's Required");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 140, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Job Title:-");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Company Name:-");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 180, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 780, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Job I'd:-");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, -1));

        lblJobId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblJobId.setText("Job-101");
        jPanel1.add(lblJobId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new HrOptionFrame().setVisible(true);        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void skills1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skills1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skills1ActionPerformed

    private void skills3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skills3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skills3ActionPerformed

    private void skills4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skills4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skills4ActionPerformed

    private void skills2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skills2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skills2ActionPerformed

    private void skills5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skills5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skills5ActionPerformed

    private void skills6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skills6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skills6ActionPerformed

    private void txtJobTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobTitleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(validateInputs()==false)        {
            JOptionPane.showMessageDialog(null,"Please fill all fields","Error !",JOptionPane.ERROR_MESSAGE);
            return ;
        }
        jobPojo job=new jobPojo();
        job.setJobId(lblJobId.getText().trim());
        job.setTitle(txtJobTitle.getText().trim());
        job.setHrId(CurrentUsers.getId());
        job.setTags(skills1.getText().trim()+","+skills2.getText().trim()+","+skills3.getText().trim()
                +","+skills4.getText().trim()+","+skills5.getText().trim()+","+skills6.getText().trim());
        job.setStatus(0);
        try{
            boolean result=jobDAO.addNewJob(job);
            if(result){
                JOptionPane.showMessageDialog(null,"Job added","Succes ",JOptionPane.INFORMATION_MESSAGE);
                clearAll();
                loadData();
                return;
                
            }
            JOptionPane.showMessageDialog(null,"Unable to add data !","Error !",JOptionPane.ERROR_MESSAGE);
                 
        }catch (SQLException ex){
                 JOptionPane.showMessageDialog(null,"DB Error ","Error !",JOptionPane.ERROR_MESSAGE);
                 ex.printStackTrace();
                //return; 
            }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void clearAll(){
        txtJobTitle.setText("");
        skills1.setText("");
        skills2.setText("");
        skills3.setText("");
        skills4.setText("");
        skills5.setText("");
        skills6.setText("");
        
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrAddNewJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrAddNewJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrAddNewJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrAddNewJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrAddNewJobFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblJobId;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField skills1;
    private javax.swing.JTextField skills2;
    private javax.swing.JTextField skills3;
    private javax.swing.JTextField skills4;
    private javax.swing.JTextField skills5;
    private javax.swing.JTextField skills6;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtJobTitle;
    // End of variables declaration//GEN-END:variables


}
