/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import trandpl.pojo.CurrentUsers;

/**
 *
 * @author __roonit
 */
public class HrOptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form HrOptionFrame
     */
    public HrOptionFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblName.setText(CurrentUsers.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnHrModule = new javax.swing.JButton();
        btnViewAllJobs = new javax.swing.JButton();
        btnViewStudents = new javax.swing.JButton();
        btnViewAllSelectedStudents = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 990, 130));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblName.setText("Ronit");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 380, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Welcome");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 100, -1));

        btnHrModule.setBackground(new java.awt.Color(173, 192, 234));
        btnHrModule.setText("Job module");
        btnHrModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHrModuleActionPerformed(evt);
            }
        });
        jPanel1.add(btnHrModule, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 280, 30));

        btnViewAllJobs.setBackground(new java.awt.Color(173, 192, 234));
        btnViewAllJobs.setText("View All Participants");
        jPanel1.add(btnViewAllJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 280, 30));

        btnViewStudents.setBackground(new java.awt.Color(173, 192, 234));
        btnViewStudents.setText("View Test Result");
        btnViewStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentsActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 280, 30));

        btnViewAllSelectedStudents.setBackground(new java.awt.Color(173, 192, 234));
        btnViewAllSelectedStudents.setText("View All Open Jobs");
        btnViewAllSelectedStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllSelectedStudentsActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewAllSelectedStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 280, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/worlp-map-in-black-h9i.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 650, 390));

        btnLogout.setBackground(new java.awt.Color(173, 192, 234));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 600, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHrModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHrModuleActionPerformed

        new HrJobOptionFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHrModuleActionPerformed

    private void btnViewStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewStudentsActionPerformed

    private void btnViewAllSelectedStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllSelectedStudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllSelectedStudentsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        new LoginFrame().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHrModule;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewAllJobs;
    private javax.swing.JButton btnViewAllSelectedStudents;
    private javax.swing.JButton btnViewStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
